### ISSUE TITLE
Left hand nav is slightly shifted up

### ISSUE THREAD

**Issue by ng-marcus** [nittygritty-uk/Atvero-Issues#12]
![image](https://user-images.githubusercontent.com/20163757/48703245-047ddf00-ebeb-11e8-9da2-4818a2f39a79.png)

**Comment by allanchaplin** [comment]
This is happening because there is a 

`SharePointDesktopNav` class added to the navigation pane.  The class sets a top margin of -14px, unsetting this class fixes the issue.

The class comes from Sharepoint so I guess it should go away eventually.

![screenshot 2018-11-21 at 12 09 26](https://user-images.githubusercontent.com/53964/48840371-5149ed00-ed86-11e8-8dc0-558d1d5dd17f.png)

**Comment by allanchaplin** [comment]
Looks like a Sharepoint update has fixed this.
