### ISSUE TITLE
Received file register

### ISSUE THREAD

**Issue by ng-marcus** [nittygritty-uk/Atvero-Issues#279]
Can we add a received file register the same as issued drawings?

Would want to filter by originator, time I think.

**Comment by LBoyle** [comment]
Parking this for now, it's more difficult than expected, we hoped we could re-use the DocRegister bits for it but we can't. 
 
Document register, for example, has Issue number on the X axis. What do we put on the X axis for received files?

**Comment by ng-marcus** [comment]
i'll have a think...

**Comment by LBoyle** [comment]
So we'll classify them by transmittalRef, and if it's not present, don't show them. 
What do we want on the table, the current revision of the doc?

**Comment by LBoyle** [comment]
This is what I have so far, any revision above 01 doesn't keep the transmittalRef, because NewRevisionAction doesn't save it. 

Blocked by #365 

I'll park this until I fix that bug after lunch.

![Screenshot from 2019-03-13 12-18-53](https://user-images.githubusercontent.com/14819677/54278558-8f178f00-458a-11e9-8c58-369c4ccedde4.png)

**Comment by LBoyle** [comment]
I used the text-orientation css property, so when the cursor is over the text, you get the text cursor rotated 90 degrees, kinda amusing, but you can highlight and copy the text easily like that.

**Comment by LBoyle** [comment]
I made some draft PRs, one with a simple solution, and another with a trade off. Will wait until in the office to get this reviewed.

**Comment by LBoyle** [comment]
PR is ready, 370

This now works pretty much the same as the Document Register, except there are some major differences, like instead of issue number, the X axis is transmittalRef. 
If a file has no transmittalRef, it doesn't appear on the chart. 

Group them by nameBlocks, filter by nameBlocks or date received.
