### ISSUE TITLE
Set document type as a required field for incoming documents

### ISSUE THREAD

**Issue by allanchaplin** [nittygritty-uk/Atvero-Issues#320]

**Comment by LBoyle** [comment]
The reason I didn't put DocumentType on the upload action row, and instead put it in the Customise modal, is because the Dropdown doesn't behave with the table, doesn't resize to match, overflows and blocks other controls. 

I was able to get the form to prevent submit if there's no DocumentType for a new received file, but you have to open the modal to set it still.

**Comment by LBoyle** [comment]
Fixed in PR 321.

It does look funny on the form, but it's use-able on a normal screen, to be discussed.
