### ISSUE TITLE
Issues: Mark an incorrect issue as 'void'

### ISSUE THREAD

**Issue by allanchaplin** [nittygritty-uk/Atvero-Issues#327]
From Stephen Higgon:

> Issue Sheets / Register - We recently issued some drawings incorrectly within Union Square that led to this thought. We couldn't roll back the revisions once issued which is correct, and I know you have set your system up the same way. However what would be useful is to mark that issue as VOID so it appears on the register list but greyed out or similar. I will produce a work flow diagram to show the flow.

**Comment by LBoyle** [comment]
So, because Issues are an immutable record, we can't ever change or delete them after they've been sent out. 

What I'll do is add a new list for Issued Transmittal metadata or something, where people can put extra information about an Issue, after it's been locked down. An example of this might be Void. 

So we'll have a normal Issue in the system, but then we'll load a few more bits of information for each Issue, that will tell us that is was voided, and when and why.

**Comment by LBoyle** [comment]
Ok, got a first version of this in for a PR, number 354

**Comment by LBoyle** [comment]
I expect there will be more on this topic, so perhaps don't close the issue.
