### ISSUE TITLE
Bulk set the size and scale

### ISSUE THREAD

**Issue by allanchaplin** [nittygritty-uk/Atvero-Issues#40]

**Comment by LBoyle** [comment]
This I think is component composition, relying on both props and state, so the interface shows that scale and size have been set, but the data we use to create our requests is from another source that doesn't reflect the actual desired state. 

Props and state are different, and we're using them interchangeably, which is bad. The batch uploader needs to be re-planned because it's over-engineered, and it's shooting me in the foot.

**Comment by LBoyle** [comment]
I misunderstood the issue, though did find a bug as per my previous comment. Some changes to related code have been made, and now I can't reproduce it. 

There is the "Bulk set" button on the batch uploader, this is the only place you can bulk-set metadata. 
When you click on a placeholder, you get to the scoped uploader, and you can't set metadata on the files you drop there, so no bulk-set
