### ISSUE TITLE
Why so many "exception UnknownException,2,Failed to update recent activity" ?

### ISSUE THREAD

**Issue by jim80** [nittygritty-uk/Atvero-Issues#405]
over 500 of these in sentry! I guess it's because it gets requested on everything, including when webpack rebuilds in dev and refreshes the page.

I might just check it's not doing multiple requests, however, since it's basically a "I was still busy doing that from the last time you asked me" sort of failure.

Or possibly just not raise an exception for it - that should kill the sentry reporting.

exception | UnhandledRejection: Types-Atvero.UnknownException,2,Failed to update recent activity

**Comment by LBoyle** [comment]
This is some kind of collision that happens when we try to record which users visit which sites. 
It's some SP error like the list item is checked out or something, I get the error like every second time I reload, but it's not consistent. 

I think the request is made two or three times because of extra re-renders related to getting the initial url and logged in user etc.

**Comment by jim80** [comment]
Thanks Louis! I guessed maybe something like that. It's not really a huge issue, but it does make maybe a bit much noise on Sentry due to the exception raising...

**Comment by allanchaplin** [comment]
I think its reasonable to spot and not report those errors to Sentry or to move those updates out of the reporting look. 

The Activity list populates the frequently used projects which does not need to be perfect.

**Comment by jim80** [comment]
I'll do that, thanks Allan.

**Comment by jim80** [comment]
Error throws are now removed, PR in, closing
