### ISSUE TITLE
DMS: clicking the filename on a new document causes an error

### ISSUE THREAD

**Issue by allanchaplin** [nittygritty-uk/Atvero-Issues#86]
Create a new DMS document, but don't publish it.
Select the document and then click the document placeholder in the list.
Red crash box, console error:
```
Toggling selection
atvero-web-part_61d47630d1cba7f5fb97cf3bfeb4c6ed.js:21 r
atvero-web-part_61d47630d1cba7f5fb97cf3bfeb4c6ed.js:21 r
atvero-web-part_61d47630d1cba7f5fb97cf3bfeb4c6ed.js:147 Array(2)
atvero-web-part_61d47630d1cba7f5fb97cf3bfeb4c6ed.js:147 (2) [Array(2), "No versions"]
```

**Comment by allanchaplin** [comment]
Should be fixed as part of #84

**Comment by LBoyle** [comment]
Was indeed fixed, but after naming changes, would never work, just print "Can't edit this file".
Got it working again for DMS files, but need to get rendition information first for DLM files, don't have it because I can't get it at page load. 
If you first select a placeholder, it loads the rendition information, then when you click on the title, the information is available, and we can open the PDF.

**Comment by LBoyle** [comment]
Desired behaviour achieved with PR #147
